### ISSUE TITLE
Add a new Command to the Game Model and Interpreter

### ISSUE THREAD

**Issue by islanddove** [j3kstrum/CodeCarnage#200]
# Background
There are currently 6 commands that can be interpreted by the game. Add another command of your own choosing. This command does not need to be supported by the GUI, but should make sense in the context of the game. 
# Task Overview
Add a single new command, based on the current interpreter framework, that modifies the state of one/both of the two players in a similar way to the other commands. You do not need to worry about adding new conditions, or any GUI support, as that can easily be added later. You are just adding a new enum, adding that enum to a switch case, and having that switch case call a new function you create. 
# Key Technical Details
You need to add code in 3 packages:

In  package interpreter/enumerations
UPDATE CODE IN 2 FILES:
The 'COMMAND' in ScriptingTypes.java should be updated to hold your command.
Command.java should also hold your new command. 

In package interpreter
Add your command in the switch statement in the executeFunction() method in ScriptCommand.java, 
and have the switch call the appropriate 'Game' function that you have created. 

In package utilities/models
Add a function in Game.java that modifies the state of the game. This function will be called by the switch statement in ScriptCommand.java that you have modified to allow this function. You can use the existing methods in this class as a guideline as to what it is possible to change. 

# Notes and Hints
You ONLY need to modify/add code in the three packages specified above. As long as you follow the same convention as the existing functions, this should be a simple task. 
 
Be creative! Don't be afraid to make your function change anything you want about the health/location/shielding/etc. of one or both of the players. Have the player self-destruct! Have the player teleport to a random location on the map! The possibilities are endless!

There is already a 7th command, 'Dodge', that has not been implemented yet. You need to implement a new command enum, so do not choose a dodging command.

**Comment by j3kstrum** [comment]
Closed by #209 .
