### ISSUE TITLE
Bug Found: Return to editor prompt not displaying

### ISSUE THREAD

**Issue by ghost** [j3kstrum/CodeCarnage#220]
A bug was found while testing CodeCarnage.

Details:

* Operating System: macOS Sierra
* Java Version, if known: Java 8 update 121

**What Happened:** 
If the game finishes while the window is not active, the pop up prompting me to return to the script editor does not appear.

**Comment by islanddove** [comment]
@noahpoz can you please try to replicate this bug, on the same system it was discovered? We will do the same on our systems to see if it is an OS issue.

**Comment by j3kstrum** [comment]
@islanddove @noahpoz have there been any updates with this? In particular, it would be interesting to know if the window does not appear or if the window does appear and is hidden in the background.

**Comment by ghost** [comment]
Ah, the issue was if I was on a different desktop than that of the game window when the game completed. The CodeCarnage window isn't in focus, so neither is the modal, so the modal will appear behind the active window on my current desktop. The modal does appear, though.

**Comment by islanddove** [comment]
@j3kstrum would you agree that we can close this, since it was not an issue with our code but an OS display issue?

**Comment by j3kstrum** [comment]
I see! Interesting quirk, but glad to know that it's not a significant bug. Thanks for bringing it up. Since it seems to be a small issue I think we'll close it for now. If anyone in the future finds this to be an issue we can open it back up and see if it's possible to address it from a user program's perspective.
